[package]
name = "libretranslate"
version = "0.1.6"
authors = ["Grant Handy <grantshandy@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Use The Libretranslate Open Source Machine Translation"
repository = "https://github.com/DefunctLizard/libretranslate-rs/"
documentation = "https://docs.rs/libretranslate"
keywords = ["translate", "language", "libretranslate", "translation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "2.0.1", features = ["json"] }
serde_json = "1.0.61"
